// Provider-neutral football portal data for server components and static export.
// data/portal.json is generated by scripts/fetch-football-data.mjs (primary) or
// scripts/fetch-api-football.mjs (dormant legacy path). When it is absent or
// invalid, the existing season fixture dataset is normalized instead.
import { existsSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { allFixtures } from './fixtures';

export interface PortalEntity {
  id: number | string | null;
  name: string | null;
  shortCode: string | null;
  imageUrl: string | null;
}

export interface PortalParticipant extends PortalEntity {
  name: string;
  role: 'home' | 'away' | null;
  position: number | null;
  winner: boolean | null;
}

export interface PortalScoreEntry {
  id: number | null;
  typeId: number | null;
  participantId: number | null;
  description: string | null;
  participant: 'home' | 'away' | null;
  goals: number | null;
}

export interface PortalEvent {
  id: number | null;
  typeId: number | null;
  typeName: string | null;
  subTypeId: number | null;
  participantId: number | null;
  playerId: number | null;
  playerName: string | null;
  relatedPlayerId: number | null;
  relatedPlayerName: string | null;
  minute: number | null;
  extraMinute: number | null;
  result: string | null;
  info: string | null;
  addition: string | null;
  injured: boolean | null;
}

export interface PortalLineup {
  id: number | null;
  participantId: number | null;
  playerId: number | null;
  playerName: string | null;
  typeId: number | null;
  positionId: number | null;
  formationField: string | null;
  jerseyNumber: number | null;
  captain: boolean | null;
  details: Array<{
    typeId: number | null;
    value: string | number | boolean | null;
  }>;
}

export interface PortalInjury {
  id: number | null;
  participantId: number | null;
  playerId: number | null;
  playerName: string | null;
  category: string | null;
  reason: string | null;
  startDate: string | null;
  endDate: string | null;
}

export interface PortalFixture {
  id: string;
  providerId: number | null;
  legacySlug?: string;
  name: string;
  startTime: string;
  resultInfo: string | null;
  seasonId: number | null;
  stageId: number | null;
  roundId: number | null;
  hasOdds: boolean;
  lastProcessedAt: string | null;
  status: {
    id: number | null;
    name: string;
    shortName: string | null;
    developerName: string | null;
    isLive: boolean;
    isFinished: boolean;
  };
  league: PortalEntity;
  round: PortalEntity;
  venue: {
    id: number | string | null;
    name: string | null;
    city: string | null;
    capacity: number | null;
    imageUrl: string | null;
  };
  participants: PortalParticipant[];
  score: {
    home: number | null;
    away: number | null;
    halfTimeHome: number | null;
    halfTimeAway: number | null;
  };
  scores: PortalScoreEntry[];
  events: PortalEvent[];
  lineups: PortalLineup[];
  injuries: PortalInjury[];
}

export interface PortalStandingRow {
  id: number | null;
  participantId: number | null;
  position: number | null;
  points: number | null;
  result: string | null;
  leagueId: number | null;
  seasonId: number | null;
  stageId: number | null;
  groupId: number | null;
  roundId: number | null;
  participant: PortalParticipant;
  details: Array<{
    typeId: number | null;
    value: string | number | boolean | null;
    description: string | null;
  }>;
  form: Array<{ fixtureId: number | null; form: string | null }>;
}

export interface PortalStandingTable {
  seasonId: number;
  leagueId: number | null;
  rows: PortalStandingRow[];
}

export interface PortalCoverage {
  dateFrom: string | null;
  dateTo: string | null;
  fixtureCount: number;
  liveFixtureCount: number;
  finishedFixtureCount: number;
  leagueCount: number;
  standingTableCount: number;
  requestedIncludes: string[];
  features: {
    fixtures: boolean;
    scores: boolean;
    statuses: boolean;
    events: boolean;
    lineups: boolean;
    injuries: boolean;
    standings: boolean;
  };
  rateLimit: {
    resetsInSeconds: number | null;
    remaining: number | null;
    requestedEntity: string | null;
  } | null;
  warnings: string[];
}

export interface PortalSnapshot {
  schemaVersion: 1;
  provider: 'api-football' | 'football-data' | 'fixtures-fallback';
  asOf: string;
  updatedAt: string;
  coverage: PortalCoverage;
  fixtures: PortalFixture[];
  standings: PortalStandingTable[];
}

let cache: PortalSnapshot | null = null;

export function portalSnapshot(): PortalSnapshot {
  if (cache) return cache;

  const provider = readSnapshot(join(process.cwd(), 'data', 'portal.json'));
  if (
    provider &&
    provider.provider !== 'fixtures-fallback' &&
    provider.fixtures.length > 0
  ) {
    cache = provider;
    return cache;
  }

  const fallbackMetadata = readSnapshot(
    join(process.cwd(), 'data', 'portal-fallback.json'),
  );
  cache = fixtureFallback(fallbackMetadata);
  return cache;
}

export function portalFixtures(limit?: number): PortalFixture[] {
  const fixtures = portalSnapshot().fixtures;
  return typeof limit === 'number'
    ? fixtures.slice(0, Math.max(0, limit))
    : fixtures;
}

export function portalFixtureById(
  id: string | number,
): PortalFixture | undefined {
  const key = String(id);
  return portalSnapshot().fixtures.find(
    (fixture) =>
      fixture.id === key ||
      String(fixture.providerId) === key ||
      fixture.legacySlug === key,
  );
}

export function portalStandings(): PortalStandingTable[] {
  return portalSnapshot().standings;
}

export function portalUsesLiveData(): boolean {
  return portalSnapshot().provider !== 'fixtures-fallback';
}

function readSnapshot(path: string): PortalSnapshot | null {
  if (!existsSync(path)) return null;
  try {
    const value: unknown = JSON.parse(readFileSync(path, 'utf8'));
    if (!isSnapshot(value)) return null;
    return value;
  } catch {
    return null;
  }
}

function isSnapshot(value: unknown): value is PortalSnapshot {
  if (!value || typeof value !== 'object') return false;
  const snapshot = value as Partial<PortalSnapshot>;
  return (
    snapshot.schemaVersion === 1 &&
    (snapshot.provider === 'api-football' ||
      snapshot.provider === 'football-data' ||
      snapshot.provider === 'fixtures-fallback') &&
    typeof snapshot.asOf === 'string' &&
    typeof snapshot.updatedAt === 'string' &&
    Boolean(snapshot.coverage && typeof snapshot.coverage === 'object') &&
    Array.isArray(snapshot.fixtures) &&
    snapshot.fixtures.every(isFixture) &&
    Array.isArray(snapshot.standings)
  );
}

function isFixture(value: unknown): value is PortalFixture {
  if (!value || typeof value !== 'object') return false;
  const fixture = value as Partial<PortalFixture>;
  return (
    typeof fixture.id === 'string' &&
    typeof fixture.name === 'string' &&
    typeof fixture.startTime === 'string' &&
    Boolean(fixture.status && typeof fixture.status.name === 'string') &&
    Boolean(fixture.league && 'id' in fixture.league) &&
    Array.isArray(fixture.participants) &&
    Array.isArray(fixture.events) &&
    Array.isArray(fixture.lineups) &&
    Array.isArray(fixture.injuries)
  );
}

function fixtureFallback(metadata: PortalSnapshot | null): PortalSnapshot {
  const now = Date.now();
  const scheduled = allFixtures()
    .filter((fixture) => new Date(fixture.date).getTime() >= now)
    .slice(0, 80)
    .map<PortalFixture>((fixture) => ({
      id: `fixture:${fixture.id}`,
      providerId: fixture.id,
      legacySlug: fixture.slug,
      name: `${fixture.home.club} vs ${fixture.away.club}`,
      startTime: new Date(fixture.date).toISOString(),
      resultInfo: null,
      seasonId: null,
      stageId: null,
      roundId: null,
      hasOdds: false,
      lastProcessedAt: null,
      status: {
        id: null,
        name: 'Scheduled',
        shortName: 'NS',
        developerName: 'NS',
        isLive: false,
        isFinished: false,
      },
      league: {
        id: fixture.league.slug,
        name: fixture.league.name,
        shortCode: null,
        imageUrl: null,
      },
      round: {
        id: null,
        name: fixture.round,
        shortCode: null,
        imageUrl: null,
      },
      venue: {
        id: null,
        name: fixture.venue,
        city: fixture.city,
        capacity: null,
        imageUrl: null,
      },
      participants: [
        {
          id: fixture.home.fdId ?? fixture.home.slug,
          name: fixture.home.club,
          shortCode: null,
          imageUrl: fixture.home.logo ?? null,
          role: 'home',
          position: null,
          winner: null,
        },
        {
          id: fixture.away.fdId ?? fixture.away.slug,
          name: fixture.away.club,
          shortCode: null,
          imageUrl: fixture.away.logo ?? null,
          role: 'away',
          position: null,
          winner: null,
        },
      ],
      score: { home: null, away: null, halfTimeHome: null, halfTimeAway: null },
      scores: [],
      events: [],
      lineups: [],
      injuries: [],
    }));

  const first = scheduled.at(0)?.startTime.slice(0, 10) ?? null;
  const last = scheduled.at(-1)?.startTime.slice(0, 10) ?? null;
  return {
    schemaVersion: 1,
    provider: 'fixtures-fallback',
    asOf: metadata?.asOf ?? '2026-07-15T00:00:00.000Z',
    updatedAt: metadata?.updatedAt ?? '2026-07-15T00:00:00.000Z',
    coverage: {
      dateFrom: first,
      dateTo: last,
      fixtureCount: scheduled.length,
      liveFixtureCount: 0,
      finishedFixtureCount: 0,
      leagueCount: new Set(scheduled.map((fixture) => fixture.league.id)).size,
      standingTableCount: 0,
      requestedIncludes: [],
      features: {
        fixtures: true,
        scores: false,
        statuses: false,
        events: false,
        lineups: false,
        injuries: false,
        standings: false,
      },
      rateLimit: null,
      warnings: [
        'Provider data is not configured; showing the existing 2026-27 schedule without live scores or match events.',
      ],
    },
    fixtures: scheduled,
    standings: [],
  };
}
